### ISSUE TITLE
Cannot convert the files

### ISSUE THREAD

**Issue by muhammad-umair-akhter** [vasile/GTFS-viz#1]
getting these error when follow the steps

(See full trace by running task with --trace)
7ctechs-Mac-mini:GTFS-viz-master 7ctech$ rake project:deploy_fusiontables
rake aborted!
no such file to load -- fusion_tables
/Users/7ctech/Downloads/GTFS-viz-master/rakefile:417
Tasks: TOP => project:deploy_fusiontables
(See full trace by running task with --trace)
7ctechs-Mac-mini:GTFS-viz-master 7ctech$ rake project:deploy_fusiontables
rake aborted!
no such file to load -- fusion_tables
/Users/7ctech/Downloads/GTFS-viz-master/rakefile:417
Tasks: TOP => project:deploy_fusiontables
(See full trace by running task with --trace)
7ctechs-Mac-mini:GTFS-viz-master 7ctech$ rake project:deploy_fusiontables --trace
*\* Invoke project:deploy_fusiontables (first_time)
*\* Execute project:deploy_fusiontables
rake aborted!
no such file to load -- fusion_tables
/System/Library/Frameworks/Ruby.framework/Versions/1.8/usr/lib/ruby/1.8/rubygems/custom_require.rb:31:in `gem_original_require'
/System/Library/Frameworks/Ruby.framework/Versions/1.8/usr/lib/ruby/1.8/rubygems/custom_require.rb:31:in`require'
/Users/7ctech/Downloads/GTFS-viz-master/rakefile:417
/Library/Ruby/Gems/1.8/gems/rake-10.1.1/lib/rake/task.rb:236:in `call'
/Library/Ruby/Gems/1.8/gems/rake-10.1.1/lib/rake/task.rb:236:in`execute'
/Library/Ruby/Gems/1.8/gems/rake-10.1.1/lib/rake/task.rb:231:in `each'
/Library/Ruby/Gems/1.8/gems/rake-10.1.1/lib/rake/task.rb:231:in`execute'
/Library/Ruby/Gems/1.8/gems/rake-10.1.1/lib/rake/task.rb:175:in `invoke_with_call_chain'
/System/Library/Frameworks/Ruby.framework/Versions/1.8/usr/lib/ruby/1.8/monitor.rb:242:in`synchronize'
/Library/Ruby/Gems/1.8/gems/rake-10.1.1/lib/rake/task.rb:168:in `invoke_with_call_chain'
/Library/Ruby/Gems/1.8/gems/rake-10.1.1/lib/rake/task.rb:161:in`invoke'
/Library/Ruby/Gems/1.8/gems/rake-10.1.1/lib/rake/application.rb:149:in `invoke_task'
/Library/Ruby/Gems/1.8/gems/rake-10.1.1/lib/rake/application.rb:106:in`top_level'
/Library/Ruby/Gems/1.8/gems/rake-10.1.1/lib/rake/application.rb:106:in `each'
/Library/Ruby/Gems/1.8/gems/rake-10.1.1/lib/rake/application.rb:106:in`top_level'
/Library/Ruby/Gems/1.8/gems/rake-10.1.1/lib/rake/application.rb:115:in `run_with_threads'
/Library/Ruby/Gems/1.8/gems/rake-10.1.1/lib/rake/application.rb:100:in`top_level'
/Library/Ruby/Gems/1.8/gems/rake-10.1.1/lib/rake/application.rb:78:in `run'
/Library/Ruby/Gems/1.8/gems/rake-10.1.1/lib/rake/application.rb:165:in`standard_exception_handling'
/Library/Ruby/Gems/1.8/gems/rake-10.1.1/lib/rake/application.rb:75:in `run'
/Library/Ruby/Gems/1.8/gems/rake-10.1.1/bin/rake:33
/usr/bin/rake:19:in`load'
/usr/bin/rake:19
Tasks: TOP => project:deploy_fusiontables
7ctechs-Mac-mini:GTFS-viz-master 7ctech$

**Comment by dkjeune** [comment]
hi, i have the same issue, can you explain the solution ?
