### ISSUE TITLE
Fusion table by using recent changes gives request access issue

### ISSUE THREAD

**Issue by Ms-Shaukat** [vasile/GTFS-viz#12]
Hi @vasile, I have used your script which you have updated 3 days ago,
All the script run successfully but when i goto fusiontable link to share table publicly, It give me error that I am not author GTFS-viz is the author.
It is also taking time to import, May be it is because request access issue.
![capture image](https://cloud.githubusercontent.com/assets/15747975/11048239/824574fc-8758-11e5-9f59-caae248e2fb3.png)

P.S. I have follow all the setting for fusion table mentioned in GTFS-viz. 
Waiting to hear you soon.

**Comment by vasile** [comment]
Which GTFS data is that ? 

The script should take care of permissions and making sure there is a `anyone` access-right
https://github.com/vasile/GTFS-viz/blob/master/inc/ft.rb#L127

Please also use `@debug` true (see ft.rb) and drop here the results

**Comment by Ms-Shaukat** [comment]
I have made this @debug true But this gives me  this error:
![screen shot 2015-11-11 at 6 45 27 pm](https://cloud.githubusercontent.com/assets/15747975/11092386/cc653dc2-88a4-11e5-986e-a49170f28e3d.png)

**Comment by vasile** [comment]
It looks like an issue with the API Console
Can you also change @debug_client to true ?

**Comment by Ms-Shaukat** [comment]
yes I have change that but still gives an error.

**Comment by vasile** [comment]
well, would be nice to debug it, so a screenshot/logfile dump would be nice 
anyway the invalid_grant errors are usually an authentication issue - so you have to doublecheck the keys generation / save task

**Comment by Ms-Shaukat** [comment]
Hi @vasile, I have setup everything as you mentioned in the Readme.
I have check my quota in credentials and it says you have done 42 request ,that's mean All the data insert by my Account. But I am still facing same request access issue.
Let me know If there is any constant in the file/ OR you have create executable file which is not working/updating correctly.
If you will run it at your end by using other/new account (just a suggestion).

Any help would be appreciated.
Thanks
