### ISSUE TITLE
Error in rake parse:gtfs_2_kml

### ISSUE THREAD

**Issue by russellhoff** [vasile/GTFS-viz#14]
Hi!

I think I've found what it seems a bug in your project... I've gone on executing commands so as to setup transit-map with a GTFS, but I'm facing a issue when executing the following command: rake parse:gtfs_2_kml.

------------------------------------------
joninazio@IN000-server:~/simulacion_gtfs/lurraldebus_pesa/GTFS-viz$ rake parse:gtfs_2_kml
/usr/local/lib/ruby/gems/2.0.0/gems/google-api-client-0.8.6/lib/google/api_client/environment.rb:35: warning: Insecure world writable dir /home/joninazio/automatizar/gtfsdb/bin in PATH, mode 040777
rake aborted!
Errno::ENOENT: No such file or directory - /home/joninazio/simulacion_gtfs/lurraldebus_pesa/GTFS-viz/inc/inc/templates/kml_placemark_shapes.xml
/home/joninazio/simulacion_gtfs/lurraldebus_pesa/GTFS-viz/inc/gtfs.rb:177:in `initialize'
/home/joninazio/simulacion_gtfs/lurraldebus_pesa/GTFS-viz/inc/gtfs.rb:177:in `open'
/home/joninazio/simulacion_gtfs/lurraldebus_pesa/GTFS-viz/inc/gtfs.rb:177:in `block in geojson_to_kml'
/home/joninazio/simulacion_gtfs/lurraldebus_pesa/GTFS-viz/inc/gtfs.rb:176:in `each'
/home/joninazio/simulacion_gtfs/lurraldebus_pesa/GTFS-viz/inc/gtfs.rb:176:in `geojson_to_kml'
/home/joninazio/simulacion_gtfs/lurraldebus_pesa/GTFS-viz/Rakefile:140:in `block (3 levels) in <top (required)>'
/home/joninazio/simulacion_gtfs/lurraldebus_pesa/GTFS-viz/Rakefile:139:in `each'
/home/joninazio/simulacion_gtfs/lurraldebus_pesa/GTFS-viz/Rakefile:139:in `block (2 levels) in <top (required)>'
Tasks: TOP => parse:gtfs_2_kml
(See full trace by running task with --trace)

Notice that the program it's looking for kml_placemark_shapes.xml file inside /home/joninazio/simulacion_gtfs/lurraldebus_pesa/GTFS-viz/inc/inc/templates/, shouldn't it be /home/joninazio/simulacion_gtfs/lurraldebus_pesa/GTFS-viz/inc/templates/?

-------------
No such file or directory - /home/joninazio/simulacion_gtfs/lurraldebus_pesa/GTFS-viz/inc/inc/templates/kml_placemark_shapes.xml
Could you lend me a hand?

Extra question: why am I getting the "Insecure world writable" warning? I've successfully cloned the project without the need of root (sudo) permission...

**Comment by russellhoff** [comment]
By the way, I don't know whether copying the content of inc/templates into inc/inc/templates works or not... This is what I'm doing right now.

**Comment by vasile** [comment]
Thanks for reporting @russellhoff , I just pushed a fix - efd7798e8d3a889772b2c68b81225cc4dc7d732b
Please pull and let me know if it works now.

**Comment by vasile** [comment]
The `Insecure world writable` error comes from the Google's gem, didn't investigate further ...
